name: mystaticsite

services:
  nginx:
    image: nginx:1.31-alpine
    restart: unless-stopped
    networks:
      daps_net:
        aliases:
          - mystaticsite

networks:
  daps_net:
    external: true
