<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Dapsman.Domain\Dapsman.Domain.csproj" />
    <ProjectReference Include="..\Dapsman.Application\Dapsman.Application.csproj" />
    <ProjectReference Include="..\Dapsman.Infrastructure\Dapsman.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.3.1</Version>
  </PropertyGroup>

</Project>
